FROM openjdk:8-jre-slim

EXPOSE 80

RUN mkdir /app

#COPY build/libs/*.jar /app/spring-boot-application.jar
COPY --from=build /home/gradle/src/build/libs/rest-app-example-1.0-SNAPSHOT.jar /app/rest-app-example-1.0-SNAPSHOT.jar

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap","-jar","/app/rest-app-example-1.0-SNAPSHOT.jar"]